
modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}"


license="MIT"

[[mods]]

modId="simpliest_hammers"

version="1.0.0"

displayName="Simpliest Hammers"

authors="IndEvo Studio" #optional



description='''A light mod adding vanilla hammers breaking in area 3x3.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.simpliest_hammers]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="${forge_version_range}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.simpliest_hammers]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"